# Generated by Django 5.2.17 on 2026-08-28 03:08

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nome_completo', models.CharField(blank=True, max_length=255, verbose_name='Nome Completo')),
                ('escola', models.CharField(blank=True, max_length=255, verbose_name='Escola Principal')),
                ('disciplina_principal', models.CharField(blank=True, max_length=120, verbose_name='Disciplina')),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='URL do Avatar')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='AssinaturaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_plano', models.CharField(choices=[('gratuito', 'Degustacao Gratis'), ('professor_geral', 'Professor Geral (Essencial)'), ('especialista_redacao', 'Especialista Redacao ENEM'), ('hub_completo', 'Hub Completo Pro')], default='gratuito', max_length=40, verbose_name='Plano Ativo')),
                ('creditos_mensais_total', models.PositiveIntegerField(default=0, verbose_name='Creditos Mensais do Plano')),
                ('creditos_utilizados_mes', models.PositiveIntegerField(default=0, verbose_name='Creditos Gastos no Mes')),
                ('creditos_avulsos_extras', models.PositiveIntegerField(default=0, verbose_name='Creditos Avulsos Comprados (Nao expiram)')),
                ('data_renovacao_ciclo', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Renovacao do Ciclo')),
                ('assinatura_ativa', models.BooleanField(default=True, verbose_name='Assinatura Ativa')),
                ('tem_acesso_diario', models.BooleanField(default=True, verbose_name='Diario Pedagogico')),
                ('tem_acesso_calendario', models.BooleanField(default=False, verbose_name='Calendario & Smart Shift')),
                ('tem_acesso_atividades', models.BooleanField(default=False, verbose_name='Gerador de Atividades BNCC')),
                ('tem_acesso_redacao', models.BooleanField(default=False, verbose_name='Corretor de Redacao ENEM')),
                ('tem_acesso_agentes', models.BooleanField(default=False, verbose_name='Hub de Agentes de IA')),
                ('tem_acesso_analytics', models.BooleanField(default=False, verbose_name='Dashboard Analytics')),
                ('tem_acesso_gamificacao', models.BooleanField(default=False, verbose_name='Gamificacao de Aulas')),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assinatura do Professor',
                'verbose_name_plural': 'Assinaturas de Professores',
            },
        ),
    ]
