# Generated by Django 5.2.17 on 2026-08-28 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeBNCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Atividade')),
                ('disciplina', models.CharField(max_length=120, verbose_name='Disciplina')),
                ('serie_ano', models.CharField(default='Ensino Médio', max_length=50, verbose_name='Série / Ano')),
                ('bimestre', models.PositiveSmallIntegerField(choices=[(1, '1º'), (2, '2º'), (3, '3º'), (4, '4º')], default=1, verbose_name='Bimestre')),
                ('habilidade_bncc_principal', models.CharField(blank=True, max_length=50, verbose_name='Habilidade BNCC Principal')),
                ('nivel_dificuldade', models.CharField(choices=[('facil', 'Fácil / Introdutória'), ('medio', 'Média / Consolidação'), ('dificil', 'Difícil / Aprofundamento'), ('enem_saeb', 'Padrão ENEM / SAEB')], default='medio', max_length=20, verbose_name='Nível de Dificuldade')),
                ('publicada', models.BooleanField(default=False, verbose_name='Publicada para os Alunos')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_bncc', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='diario.turma')),
            ],
            options={
                'verbose_name': 'Atividade BNCC',
                'verbose_name_plural': 'Atividades BNCC',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem da Questão')),
                ('tipo', models.CharField(choices=[('multipla_escolha', 'Múltipla Escolha (A, B, C, D)'), ('discursiva', 'Discursiva / Dissertativa')], default='multipla_escolha', max_length=30, verbose_name='Tipo da Questão')),
                ('texto_base', models.TextField(blank=True, verbose_name='Texto Motivador / Contexto')),
                ('enunciado', models.TextField(verbose_name='Enunciado da Questão')),
                ('habilidade_bncc', models.CharField(blank=True, max_length=50, verbose_name='Código da Habilidade BNCC')),
                ('alternativas', models.JSONField(blank=True, default=list, verbose_name='Alternativas e Justificativas')),
                ('rubrica_correcao', models.TextField(blank=True, verbose_name='Critérios / Rubrica de Correção IA')),
                ('pontos', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Pontuação da Questão')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='atividades.atividadebncc')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='RespostaEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_aluno', models.TextField(verbose_name='Resposta Enviada pelo Aluno')),
                ('correta', models.BooleanField(blank=True, null=True, verbose_name='Correta')),
                ('nota_atribuida', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota Atribuída')),
                ('feedback_ia', models.TextField(blank=True, verbose_name='Feedback Pedagógico da IA')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_atividades', to='diario.estudante')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='atividades.questao')),
            ],
            options={
                'verbose_name': 'Resposta do Estudante',
                'verbose_name_plural': 'Respostas dos Estudantes',
                'unique_together': {('questao', 'estudante')},
            },
        ),
    ]
