# Generated by Django 5.2.17 on 2026-08-28 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscolaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Escola')),
                ('codigo_mec', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código MEC/INEP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'db_table': 'escolas',
            },
        ),
        migrations.CreateModel(
            name='GradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(default='1.0.0', max_length=50, verbose_name='Versão da Grade')),
                ('ativa', models.BooleanField(default=True, verbose_name='Grade Vigente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='horario_escolar_inteligente.escolamodel')),
            ],
            options={
                'verbose_name': 'Grade Escolar',
                'verbose_name_plural': 'Grades Escolares',
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='ChangelogPermutaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Operação')),
                ('tipo_operacao', models.CharField(default='Permuta', max_length=50, verbose_name='Tipo de Operação')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada do Remanejamento')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelogs', to='horario_escolar_inteligente.grademodel')),
            ],
            options={
                'verbose_name': 'Changelog de Permuta',
                'verbose_name_plural': 'Changelogs de Permutas',
                'db_table': 'changelog_permutas',
            },
        ),
        migrations.CreateModel(
            name='ProfessorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Professor')),
                ('area_bncc', models.CharField(choices=[('Linguagens', 'Linguagens e suas Tecnologias'), ('Matemática', 'Matemática e suas Tecnologias'), ('Natureza', 'Ciências da Natureza e suas Tecnologias'), ('Humanas', 'Ciências Humanas e Sociais Aplicadas'), ('Especiais', 'Espaços Especiais / Diversificada')], max_length=50, verbose_name='Área BNCC')),
                ('dia_planejamento', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dia de Planejamento (Folga)')),
                ('turno_planejamento', models.CharField(blank=True, max_length=30, null=True, verbose_name='Turno de Planejamento')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='horario_escolar_inteligente.escolamodel')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'db_table': 'professores',
                'unique_together': {('escola', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='SalaTematicaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Sala (ex: Sala L1)')),
                ('area_bncc', models.CharField(max_length=50, verbose_name='Área BNCC Vinculada')),
                ('tipologia', models.CharField(default='Teórica', max_length=50, verbose_name='Tipologia (Teórica, Prática, Lab)')),
                ('capacidade', models.IntegerField(default=40, verbose_name='Capacidade de Alunos')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_tematicas', to='horario_escolar_inteligente.escolamodel')),
            ],
            options={
                'verbose_name': 'Sala Temática',
                'verbose_name_plural': 'Salas Temáticas',
                'db_table': 'salas_tematicas',
                'unique_together': {('escola', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='TurmaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Turma (ex: 1º ANO - 101)')),
                ('serie', models.CharField(max_length=50, verbose_name='Série/Ano')),
                ('total_aulas_semana', models.IntegerField(default=45, verbose_name='Total de Aulas Semanais')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='horario_escolar_inteligente.escolamodel')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'turmas',
                'unique_together': {('escola', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='SlotGradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=30, verbose_name='Dia da Semana')),
                ('aula', models.IntegerField(verbose_name='Tempo de Aula (1 a 9)')),
                ('disciplina', models.CharField(max_length=100, verbose_name='Disciplina')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='horario_escolar_inteligente.grademodel')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots_alocados', to='horario_escolar_inteligente.professormodel')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots_alocados', to='horario_escolar_inteligente.salatematicamodel')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots_alocados', to='horario_escolar_inteligente.turmamodel')),
            ],
            options={
                'verbose_name': 'Slot de Grade',
                'verbose_name_plural': 'Slots de Grade',
                'db_table': 'slots_grade',
                'indexes': [models.Index(fields=['professor', 'dia', 'aula'], name='idx_slot_prof_dia_aula'), models.Index(fields=['sala', 'dia', 'aula'], name='idx_slot_sala_dia_aula'), models.Index(fields=['turma', 'dia', 'aula'], name='idx_slot_turma_dia_aula'), models.Index(fields=['grade'], name='idx_slot_grade')],
            },
        ),
        migrations.CreateModel(
            name='MatrizCurricularModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100, verbose_name='Disciplina')),
                ('carga_semanal', models.IntegerField(verbose_name='Carga Horária Semanal (aulas)')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrizes', to='horario_escolar_inteligente.turmamodel')),
            ],
            options={
                'verbose_name': 'Matriz Curricular',
                'verbose_name_plural': 'Matrizes Curriculares',
                'db_table': 'matrizes_curriculares',
                'unique_together': {('turma', 'disciplina')},
            },
        ),
    ]
