# Generated by Django 5.2.17 on 2026-08-28 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaRedacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Frase-Tema Oficial')),
                ('ano_enem', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano do ENEM (se aplicável)')),
                ('textos_motivadores', models.JSONField(blank=True, default=list, verbose_name='Textos Motivadores')),
                ('orientacoes', models.TextField(blank=True, verbose_name='Orientações e Instruções')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas_redacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tema de Redação',
                'verbose_name_plural': 'Temas de Redação',
                'ordering': ['-ano_enem', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SubmissaoRedacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno_avulso', models.CharField(blank=True, max_length=255, verbose_name='Nome do Aluno (se avulso)')),
                ('imagem_url', models.URLField(blank=True, max_length=500, verbose_name='URL da Imagem da Folha')),
                ('texto_extraido_ocr', models.TextField(blank=True, verbose_name='Texto Extraído via OCR')),
                ('nota_c1', models.PositiveSmallIntegerField(default=0, verbose_name='C1 - Norma Culta')),
                ('nota_c2', models.PositiveSmallIntegerField(default=0, verbose_name='C2 - Tema e Repertório')),
                ('nota_c3', models.PositiveSmallIntegerField(default=0, verbose_name='C3 - Projeto de Texto')),
                ('nota_c4', models.PositiveSmallIntegerField(default=0, verbose_name='C4 - Coesão e Conectivos')),
                ('nota_c5', models.PositiveSmallIntegerField(default=0, verbose_name='C5 - Proposta de Intervenção')),
                ('nota_total', models.PositiveSmallIntegerField(default=0, verbose_name='Nota Final (0 a 1000)')),
                ('laudo_pedagogico', models.JSONField(blank=True, default=dict, verbose_name='Laudo de Avaliação IA')),
                ('status', models.CharField(choices=[('pendente', 'Pendente na Fila Celery'), ('processando_ocr', 'Processando OpenCV & OCR'), ('avaliando_ia', 'Avaliando Competências com IA'), ('concluida', 'Correção Concluída'), ('erro', 'Erro no Processamento')], default='pendente', max_length=30, verbose_name='Status do Processamento')),
                ('erro_detalhe', models.TextField(blank=True, verbose_name='Detalhes do Erro')),
                ('tempo_processamento_ms', models.PositiveIntegerField(default=0, verbose_name='Tempo de Processamento (ms)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('estudante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redacoes', to='diario.estudante')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redacoes_corrigidas', to=settings.AUTH_USER_MODEL)),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissoes', to='redacao.temaredacao')),
            ],
            options={
                'verbose_name': 'Submissão de Redação',
                'verbose_name_plural': 'Submissões de Redações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
