# Generated by Django 5.2.17 on 2026-08-28 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmentaTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.PositiveSmallIntegerField(choices=[(1, '1º'), (2, '2º'), (3, '3º'), (4, '4º')], verbose_name='Bimestre')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem Cronológica na Ementa')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Tema / Aula')),
                ('habilidade_bncc', models.CharField(blank=True, max_length=50, verbose_name='Código da Habilidade BNCC')),
                ('objetivos', models.TextField(blank=True, verbose_name='Objetivos de Aprendizagem')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas_ementa', to='diario.turma')),
            ],
            options={
                'verbose_name': 'Tema da Ementa',
                'verbose_name_plural': 'Temas da Ementa',
                'ordering': ['bimestre', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='AulaAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, verbose_name='Data da Aula')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Término')),
                ('conteudo_customizado', models.CharField(blank=True, max_length=255, verbose_name='Conteúdo Customizado')),
                ('status', models.CharField(choices=[('prevista', 'Prevista'), ('lecionada', 'Lecionada com Sucesso'), ('remanejada', 'Remanejada (Smart Shift)'), ('cancelada', 'Cancelada'), ('feriado', 'Feriado / Recesso')], default='prevista', max_length=20, verbose_name='Status da Aula')),
                ('motivo_remanejamento', models.CharField(blank=True, max_length=255, verbose_name='Motivo de Alteração')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='diario.turma')),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas_agendadas', to='calendario.ementatema')),
            ],
            options={
                'verbose_name': 'Aula Agendada',
                'verbose_name_plural': 'Aulas Agendadas',
                'ordering': ['data', 'horario_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, verbose_name='Data do Evento')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Evento')),
                ('tipo', models.CharField(choices=[('feriado', 'Feriado Nacional / Municipal'), ('recesso', 'Recesso Escolar'), ('conselho_classe', 'Conselho de Classe'), ('planejamento', 'Dia de Planejamento Pedagógico'), ('evento_escolar', 'Evento / Feira Cultural')], default='feriado', max_length=30, verbose_name='Tipo do Evento')),
                ('bloqueia_aulas', models.BooleanField(default=True, verbose_name='Bloqueia Agendamento de Aulas')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_calendario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento do Calendário',
                'verbose_name_plural': 'Eventos do Calendário',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='GradeHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], verbose_name='Dia da Semana')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Término')),
                ('sala', models.CharField(blank=True, max_length=50, verbose_name='Sala de Aula')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_horarias', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='diario.turma')),
            ],
            options={
                'verbose_name': 'Grade Horária',
                'verbose_name_plural': 'Grades Horárias',
                'ordering': ['dia_semana', 'horario_inicio'],
            },
        ),
    ]
