# Generated by Django 5.2.17 on 2026-08-28 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da Turma')),
                ('ano_letivo', models.PositiveIntegerField(default=2026, verbose_name='Ano Letivo')),
                ('disciplina', models.CharField(max_length=120, verbose_name='Disciplina')),
                ('turno', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('noturno', 'Noturno'), ('integral', 'Integral')], default='matutino', max_length=20, verbose_name='Turno')),
                ('configuracao_pesos', models.JSONField(blank=True, default=dict, help_text='Ex: {"peso_simulado": 4.0, "peso_atividades": 6.0, "media_aprovacao": 6.0}', verbose_name='Configuracao de Pesos e Media')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Estudante')),
                ('data_nascimento', models.CharField(blank=True, max_length=10, verbose_name='Data de Nascimento (DDMM)')),
                ('login_aluno', models.CharField(db_index=True, max_length=100, verbose_name='Login Unico do Aluno')),
                ('numero_chamada', models.PositiveIntegerField(default=1, verbose_name='Numero de Chamada')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudantes', to='diario.turma')),
            ],
            options={
                'verbose_name': 'Estudante',
                'verbose_name_plural': 'Estudantes',
                'ordering': ['numero_chamada', 'nome'],
                'unique_together': {('turma', 'login_aluno')},
            },
        ),
        migrations.CreateModel(
            name='NotaBimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.PositiveSmallIntegerField(choices=[(1, '1º'), (2, '2º'), (3, '3º'), (4, '4º')], verbose_name='Bimestre')),
                ('nota_simulado', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota Simulado')),
                ('nota_atividades', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota Atividades')),
                ('nota_recuperacao', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota Recuperacao')),
                ('media_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Media Final Calculada')),
                ('faltas', models.PositiveIntegerField(default=0, verbose_name='Faltas no Bimestre')),
                ('status', models.CharField(choices=[('em_curso', 'Em Curso'), ('aprovado', 'Aprovado'), ('recuperacao', 'Em Recuperacao'), ('critico', 'Risco Critico')], default='em_curso', max_length=20, verbose_name='Status Pedagogico')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='diario.estudante')),
            ],
            options={
                'verbose_name': 'Nota Bimestral',
                'verbose_name_plural': 'Notas Bimestrais',
                'ordering': ['bimestre'],
                'unique_together': {('estudante', 'bimestre')},
            },
        ),
    ]
