"""add_turma_to_planejamento

Revision ID: 130186a214b8
Revises: 862f195eda4d
Create Date: 2026-05-21 20:59:25.244639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '130186a214b8'
down_revision: Union[str, Sequence[str], None] = '862f195eda4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planejamentos_anuais', sa.Column('turma', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planejamentos_anuais', 'turma')
    # ### end Alembic commands ###
