"""add_planejamento_horario

Revision ID: 862f195eda4d
Revises: a5879b5d8593
Create Date: 2026-05-21 17:38:49.618762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '862f195eda4d'
down_revision: Union[str, Sequence[str], None] = 'a5879b5d8593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planejamento_horarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planejamento_anual_id', sa.UUID(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('horario_inicio', sa.String(length=5), nullable=False),
    sa.Column('duracao_minutos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planejamento_anual_id'], ['planejamentos_anuais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planejamento_horarios')
    # ### end Alembic commands ###
