"""initial

Revision ID: a5879b5d8593
Revises: 
Create Date: 2026-05-20 23:23:40.494613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5879b5d8593'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendario_escolar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professor_id', sa.String(length=255), nullable=False),
    sa.Column('ano_letivo', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=False),
    sa.Column('dias_semana', sa.String(length=100), nullable=False),
    sa.Column('horario_inicio', sa.String(length=5), nullable=False),
    sa.Column('duracao_aula_minutos', sa.Integer(), nullable=False),
    sa.Column('feriados_json', sa.String(), nullable=True),
    sa.Column('fonte_calendario', sa.String(length=50), nullable=False),
    sa.Column('google_tokens_json', sa.Text(), nullable=True),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendario_escolar_professor_id'), 'calendario_escolar', ['professor_id'], unique=False)
    op.create_table('planejamentos_anuais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professor_id', sa.String(length=255), nullable=False),
    sa.Column('disciplina', sa.String(length=255), nullable=False),
    sa.Column('serie', sa.String(length=100), nullable=False),
    sa.Column('carga_horaria_semanal', sa.Integer(), nullable=False),
    sa.Column('carga_horaria_anual', sa.Integer(), nullable=False),
    sa.Column('ano_letivo', sa.Integer(), nullable=False),
    sa.Column('temas_curriculares', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planejamentos_anuais_professor_id'), 'planejamentos_anuais', ['professor_id'], unique=False)
    op.create_table('planejamentos_bimestrais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planejamento_anual_id', sa.UUID(), nullable=False),
    sa.Column('bimestre', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('temas_principais', sa.Text(), nullable=True),
    sa.Column('carga_horaria', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planejamento_anual_id'], ['planejamentos_anuais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conteudos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planejamento_bimestral_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('prioridade', sa.Integer(), nullable=False),
    sa.Column('carga_horaria_estimada', sa.Integer(), nullable=False),
    sa.Column('habilidade_bncc', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planejamento_bimestral_id'], ['planejamentos_bimestrais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aulas_plano',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planejamento_bimestral_id', sa.UUID(), nullable=False),
    sa.Column('conteudo_id', sa.UUID(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('metodologia', sa.Text(), nullable=True),
    sa.Column('recursos', sa.Text(), nullable=True),
    sa.Column('duracao_minutos', sa.Integer(), nullable=False),
    sa.Column('status_execucao', sa.String(length=50), nullable=False),
    sa.Column('realizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conteudo_id'], ['conteudos.id'], ),
    sa.ForeignKeyConstraint(['planejamento_bimestral_id'], ['planejamentos_bimestrais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequencias_didaticas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conteudo_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('objetivo_geral', sa.Text(), nullable=False),
    sa.Column('objetivos_especificos', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('metodologia', sa.Text(), nullable=False),
    sa.Column('recursos', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('etapas', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('avaliacao', sa.Text(), nullable=False),
    sa.Column('referencias', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conteudo_id'], ['conteudos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conteudo_id')
    )
    op.create_table('observacoes_aula',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aula_id', sa.UUID(), nullable=False),
    sa.Column('professor_id', sa.String(length=255), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('engajamento', sa.String(length=20), nullable=True),
    sa.Column('dificuldades', sa.Text(), nullable=True),
    sa.Column('recursos_utilizados', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas_plano.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reagendamentos_conteudo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aula_plano_original_id', sa.UUID(), nullable=False),
    sa.Column('conteudo_id', sa.UUID(), nullable=False),
    sa.Column('nova_data_proposta', sa.DateTime(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('professor_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aula_plano_original_id'], ['aulas_plano.id'], ),
    sa.ForeignKeyConstraint(['conteudo_id'], ['conteudos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reagendamentos_conteudo')
    op.drop_table('observacoes_aula')
    op.drop_table('sequencias_didaticas')
    op.drop_table('aulas_plano')
    op.drop_table('conteudos')
    op.drop_table('planejamentos_bimestrais')
    op.drop_index(op.f('ix_planejamentos_anuais_professor_id'), table_name='planejamentos_anuais')
    op.drop_table('planejamentos_anuais')
    op.drop_index(op.f('ix_calendario_escolar_professor_id'), table_name='calendario_escolar')
    op.drop_table('calendario_escolar')
    # ### end Alembic commands ###
